# jaffle_shop:
#   outputs:
#     dev:
#       type: postgres
#       threads: 1
#       host: postgres
#       port: 5432
#       user: postgres
#       pass: postgres
#       dbname: postgres
#       schema: postgres
#   target: dev
jaffle_shop:
  outputs:
    dev:
      type: clickhouse
      threads: 1
      host: clickhouse
      port: 8123
      user: admin
      password: admin
      dbname: default
      schema: default
  target: dev
