version: '3.1'
services:
  scheduler:
    networks:
      - lakehouse
    volumes:
      - ./dbt:/usr/local/airflow/dbt:rw
  
  webserver:
    networks:
      - lakehouse
    volumes:
      - ./dbt:/usr/local/airflow/dbt:rw
  
  triggerer:
    networks:
      - lakehouse
    volumes:
      - ./dbt:/usr/local/airflow/dbt:rw
  
  postgres:
    networks:
      - lakehouse

  clickhouse:
    image: clickhouse:24.11.3
    container_name: clickhouse
    restart: always
    ports:
      - 8123:8123
      - 9000:9000
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin
    networks:
      - lakehouse

  postgres_v2:
    image: postgres:15
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - lakehouse
  
  minio:
    image: minio/minio:RELEASE.2025-02-07T23-21-09Z-cpuv1
    container_name: minio
    restart: always
    ports:
      - 9001:9001
      - 9002:9002
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server --address ":9002" --console-address ":9001" /data
    networks:
      - lakehouse

  sqlpad:
    image: sqlpad/sqlpad:7
    hostname: 'sqlpad'
    ports:
      - 3000:3000
    environment:
      SQLPAD_ADMIN: admin
      SQLPAD_ADMIN_PASSWORD: admin
      SQLPAD_APP_LOG_LEVEL: debug
      SQLPAD_WEB_LOG_LEVEL: warn
      SQLPAD_SEED_DATA_PATH: /etc/sqlpad/seed-data
    networks:
      - lakehouse


networks:
  lakehouse:
    name: lakehouse
    driver: bridge