version: 2

models:
  - name: d_stg_customers
    depends_on:
      - ref: stg_order
      - ref: stg_payment
    config:
        meta:
          owner: team_a
          update_type: 'INST'
          schedule_interval: '30 23 * * *'
          schema: 'postgres'
          table_name: 'stg_customers'
    description: '{{ doc("__overview_v2__") }}'
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: d_stg_orders
    depends_on:
      - ref: stg_order
    config:
        meta:
          owner: team_b
          update_type: 'INST'
          schedule_interval: '30 23 * * *'
          schema: 'postgres'
          table_name: 'stg_orders'
    description: '{{ doc("__overview_v2__") }}'
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

  - name: d_stg_payments
    depends_on:
      - ref: stg_order
    config:
        meta:
          owner: team_c
          update_type: 'INST'
          schedule_interval: '30 23 * * *'
          schema: 'postgres'
          table_name: 'stg_payments'
    description: '{{ doc("__overview_v2__") }}'
    columns:
      - name: payment_id
        tests:
          - unique
          - not_null
      - name: payment_method
        tests:
          - accepted_values:
              values: ['credit_card', 'coupon', 'bank_transfer', 'gift_card']
