version: 2

models:
  - name: stg_orders
    config:
        meta:
          dag_id: bussiness_flow
          dag_structure_version: v3
          owner: team_b
          update_type: 'INST'
          schedule_interval: '*/5 * * * *'
          schema: 'postgres'
          table_name: 'stg_orders'
    description: '{{ doc("__overview_v2__") }}'
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

